### ISSUE TITLE
Output Pdf Page Num with Obsidian Style 

### ISSUE THREAD

**Issue by Quorafind** [akaalias/obsidian-extract-pdf-highlights#2]
After obsidian ver 0.10.8, obsidian allows you use [[book.pdf#page=3]] to jump to page 3 of pdf.

So is it possible to add a feature to output those highlights and notes with this style?

> BLABLABLABLA ——[[book.pdf#page=3]]

**Comment by akaalias** [comment]
Hi @Quorafind! Great idea and definitely possible IF I can get the plugin to work again (https://github.com/akaalias/obsidian-extract-pdf-highlights/releases/tag/0.0.3 for details)
