### ISSUE TITLE
Whats the current status concerning the PDF handling in Obsidian?

### ISSUE THREAD

**Issue by benytzlich** [akaalias/obsidian-extract-pdf-highlights#4]
I just try to understand the extent of problem. Its a very power - and useful tool.

**Comment by akaalias** [comment]
Hey there! I just pushed the fix, I finally took the time to do the necessary full refactor. This is release 0.0.4 (https://github.com/akaalias/obsidian-extract-pdf-highlights/releases/tag/0.0.4) 

To update, just use the Obsidian plugin update function and it should work again!

**Comment by benytzlich** [comment]
nice! Thanks!
