### ISSUE TITLE
No effect when clicking pdf button

### ISSUE THREAD

**Issue by plandrem** [akaalias/obsidian-extract-pdf-highlights#9]
I tried the following:

- install + activate plugin
- open a pdf in PDF Expert
- highlight a few sentences
- copy the pdf into Obsidian vault
- open in Obsidian (I can see the highlighted text)
- click PDF button

Nothing happens. Does it matter which tool is used to create the highlights?

**Comment by plandrem** [comment]
Seems to have resolved

**Comment by bezirganyan** [comment]
I have the same issue. I get no effect from clicking the button in a highlighted PDF
